// <auto-generated />
namespace Angular_Crud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(field));
        
        string IMigrationMetadata.Id
        {
            get { return "201706221243265_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
